"""Add accommodations, search history, and favorites

Revision ID: ad4fba205c74
Revises: 
Create Date: 2026-06-22 13:50:18.825622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad4fba205c74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('price_per_night', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=False),
    sa.Column('amenities', sa.JSON(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('distance_center', sa.Float(), nullable=False),
    sa.Column('distance_airport', sa.Float(), nullable=False),
    sa.Column('distance_beach', sa.Float(), nullable=True),
    sa.Column('distance_sightseeing', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_city'), 'accommodations', ['city'], unique=False)
    op.create_index('ix_accommodations_city_type', 'accommodations', ['city', 'type'], unique=False)
    op.create_index(op.f('ix_accommodations_id'), 'accommodations', ['id'], unique=False)
    op.create_index(op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=False)
    op.create_index('ix_accommodations_price', 'accommodations', ['price_per_night'], unique=False)
    op.create_index(op.f('ix_accommodations_type'), 'accommodations', ['type'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_type', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_favorites_item_id'), 'favorites', ['item_id'], unique=False)
    op.create_index(op.f('ix_favorites_item_type'), 'favorites', ['item_type'], unique=False)
    op.create_table('flight_price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('flight_id', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_price_history_flight_id'), 'flight_price_history', ['flight_id'], unique=False)
    op.create_table('flights',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('airline', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('base_price_brl', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('stops', sa.Integer(), nullable=False),
    sa.Column('cabin_class', sa.String(), nullable=False),
    sa.Column('booking_url', sa.String(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flights_collected_at', 'flights', ['collected_at'], unique=False)
    op.create_index(op.f('ix_flights_id'), 'flights', ['id'], unique=False)
    op.create_index('ix_flights_origin_destination', 'flights', ['origin', 'destination'], unique=False)
    op.create_index('ix_flights_price', 'flights', ['price'], unique=False)
    op.create_table('price_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telegram_chat_id', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alerts_email'), 'price_alerts', ['email'], unique=False)
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('return_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adults', sa.Integer(), nullable=False),
    sa.Column('searched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    op.drop_index(op.f('ix_price_alerts_email'), table_name='price_alerts')
    op.drop_table('price_alerts')
    op.drop_index('ix_flights_price', table_name='flights')
    op.drop_index('ix_flights_origin_destination', table_name='flights')
    op.drop_index(op.f('ix_flights_id'), table_name='flights')
    op.drop_index('ix_flights_collected_at', table_name='flights')
    op.drop_table('flights')
    op.drop_index(op.f('ix_flight_price_history_flight_id'), table_name='flight_price_history')
    op.drop_table('flight_price_history')
    op.drop_index(op.f('ix_favorites_item_type'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_item_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_accommodations_type'), table_name='accommodations')
    op.drop_index('ix_accommodations_price', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_id'), table_name='accommodations')
    op.drop_index('ix_accommodations_city_type', table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_city'), table_name='accommodations')
    op.drop_table('accommodations')
    # ### end Alembic commands ###
